### ISSUE TITLE
Unbound Identifier proyecto.rkt

### ISSUE THREAD

**Issue by Cvaztian** [kevv87/RacketRubik#13]
En la branch rotaciones, archivo "proyecto.rkt", existe un unbound identifier en la seccion de interfaz. Esto desde el commit "**Union logica con interfaz**"  **(1/5/2020)**; se sospecha proviene de algun commit anterior.
Favor revisar, xoxo

**Comment by kevv87** [comment]
_uwu rawr_ Here
Will check commits tomorrow.

**Comment by kevv87** [comment]
Mae es que usted hizo una función que se llama length, entonces sobreescribe la función length de Racket, que yo uso en varios lugares, so, cambiele el nombre y sus apariciones, please:

Línea 423, función length, cambiar nombre

**Comment by kevv87** [comment]
@Cvaztian

**Comment by kevv87** [comment]
Resuelva esta penga  @Cvaztian

**Comment by Cvaztian** [comment]
El problema del nombre ya fue solucionado. Ahora existe un bug en el cual al rotar las caras, el cubo se cubre de color negro. Any ideas?

**Comment by kevv87** [comment]
Dayum, let me see

**Comment by kevv87** [comment]
No me pasa eso en el commit 
63fe7c5aa2f78585f17ea0eb2844c9a60bd5b7fc

**Comment by kevv87** [comment]
De hecho funca de lo más bien xD
