### ISSUE TITLE
Orden de colores en cubitos

### ISSUE THREAD

**Issue by Cvaztian** [kevv87/RacketRubik#14]
@kevv87 
Como habiamos hablado, el orden es: frente, derecha, atras, izquierda, arriba y abajo. Ingresado por caras horizontales recorriendo de izquierda a derecha hacia el eje Z (fondo), los elementos del cubo serian (?):

((rgba "white") (rgba "orange") (rgba "blue") (rgba "white") (rgba "blue") (rgba "white") (rgba "red") (rgba "blue") (rgba "orange") (rgba "blue") (rgba "blue") (rgba "red") (rgba "blue") (rgba "yellow") (rgba "orange") (rgba "blue") (rgba "yellow") (rgba "blue") (rgba "red") (rgba "yellow") (rgba "blue") (rgba "white") (rgba "orange") (rgba "white") (rgba "white") (rgba "red") (rgba "orange") () (rgba "red") (rgba "yellow") (rgba "orange") (rgba "yellow") (rgba "red") (rgba "yellow") (rgba "white") (rgba "orange") (rgba "green") (rgba "white") (rgba "green") (rgba "white") (rgba "red") (rgba "green") (rgba "orange") (rgba "green") (rgba "green") (rgba "red") (rgba "green") (rgba "yellow") (rgba "orange") (rgba "green") (rgba "yellow") (rgba "green") (rgba "red") (rgba "yellow") (rgba "green"))

Favor confirmar.

**Comment by kevv87** [comment]
Mae ahí está nada más chorreando los colores, no sé si eso de su lado está bien? O sea, recuerde que al menos en la interfaz se hacen sublistas por cada cara movil y por cada fila de la cara móvil
Digamos que sí está contemplando eso, en ese casoo... Bueno suae xD a qué cubo quiere que lo compare? 
@Cvaztian

**Comment by Cvaztian** [comment]
Burh
No hay formato porque lo acabo de copiar en el Issue viendo el cubo en la **aplicacion movil Cube Rubik**; es irrelevante. Lo que ocupo es que compare la forma en la que usted "chorrearia" los colores viendo el cubo con la lista que yo "choree" y que me diga si son iguales.
@kevv87

**Comment by kevv87** [comment]
@Cvaztian Aye aye captain, it's fine.

**Comment by Cvaztian** [comment]
thnx m8
